[package]
name = "retty"
version = "0.17.0"
authors = ["Rusty Rain <y@liu.mx>"]
edition = "2021"
description = "Retty — an asynchronous Rust networking framework that makes it easy to build protocols, application clients/servers."
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/retty"
repository = "https://github.com/retty-io/retty"
homepage = "https://retty.io"
keywords = ["networking", "protocols"]
categories = [ "network-programming", "asynchronous" ]

[features]
default = ["runtime-tokio"]
runtime-tokio = ["tokio/rt", "tokio/net", "tokio/sync", "tokio/io-util", "tokio/time", "tokio/macros", "async-transport/runtime-tokio", "waitgroup", "async-trait"]
runtime-async-std = ["async-io", "async-std", "futures-lite", "tokio/macros", "async-transport/runtime-async-std", "waitgroup", "async-trait"]
metal-io = ["mio", "mio-extras"]

[dependencies]
bytes = "1.4.0"
log = "0.4.17"
waitgroup = { version = "0.1.2", optional = true }
async-trait = { version = "0.1.64", optional = true }
async-io = { version = "1.12.0", optional = true }
async-std = { version = "1.12.0", optional = true }
futures-lite = { version = "1.12.0", optional = true }
tokio = { version = "1.25.0", optional = true }
async-transport = { version = "0.3.2", default-features = false, optional = true }
mio = { version = "0.6.23", optional = true }
mio-extras = { version = "2.0.6", optional = true }

[dev-dependencies]
tokio = { version = "1.25.0", features = ["full"] }
futures = "0.3.26"
chrono = "0.4.23"
env_logger = "0.10.0"
clap = { version = "4.1.4", features = ["derive"] }
anyhow = "1.0.69"

[[example]]
name = "echo_tcp_server"
path = "examples/echo/echo_tcp_server.rs"

[[example]]
name = "echo_tcp_client"
path = "examples/echo/echo_tcp_client.rs"

[[example]]
name = "echo_udp_server"
path = "examples/echo/echo_udp_server.rs"

[[example]]
name = "echo_udp_client"
path = "examples/echo/echo_udp_client.rs"

[[example]]
name = "chat_tcp_client"
path = "examples/chat/chat_tcp_client.rs"

[[example]]
name = "chat_tcp_server"
path = "examples/chat/chat_tcp_server.rs"

[[example]]
name = "mio_udp_server"
path = "examples/mio/mio_udp_server.rs"
required-features = ["metal-io"]

[[example]]
name = "mio_udp_client"
path = "examples/mio/mio_udp_client.rs"
required-features = ["metal-io"]

[[example]]
name = "chat_udp_ecn_client"
path = "examples/chat/chat_udp_ecn_client.rs"

[[example]]
name = "chat_udp_ecn_server"
path = "examples/chat/chat_udp_ecn_server.rs"
